/*******************************************************************************
 * Copyright (c) 2013 BSI Business Systems Integration AG.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     BSI Business Systems Integration AG - initial API and implementation
 ******************************************************************************/
package org.eclipsescout.demo.minicrm.shared.services.process;

import java.util.Date;
import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.tablefield.AbstractTableFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ChatFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public ChatFormData() {
  }

  /**
   * access method for property BuddyName.
   */
  public String getBuddyName() {
    return getBuddyNameProperty().getValue();
  }

  /**
   * access method for property BuddyName.
   */
  public void setBuddyName(String buddyName) {
    getBuddyNameProperty().setValue(buddyName);
  }

  public BuddyNameProperty getBuddyNameProperty() {
    return getPropertyByClass(BuddyNameProperty.class);
  }

  public History getHistory() {
    return getFieldByClass(History.class);
  }

  public Message getMessage() {
    return getFieldByClass(Message.class);
  }

  /**
   * access method for property UserName.
   */
  public String getUserName() {
    return getUserNameProperty().getValue();
  }

  /**
   * access method for property UserName.
   */
  public void setUserName(String userName) {
    getUserNameProperty().setValue(userName);
  }

  public UserNameProperty getUserNameProperty() {
    return getPropertyByClass(UserNameProperty.class);
  }

  public static class BuddyNameProperty extends AbstractPropertyData<String> {

    private static final long serialVersionUID = 1L;

    public BuddyNameProperty() {
    }
  }

  public static class History extends AbstractTableFieldData {

    private static final long serialVersionUID = 1L;
    public static final int TYPE_COLUMN_ID = 0;
    public static final int SENDER_COLUMN_ID = 1;
    public static final int RECEIVER_COLUMN_ID = 2;
    public static final int MESSAGE_COLUMN_ID = 3;
    public static final int TIME_COLUMN_ID = 4;
    public static final int RECEIVING_NODE_COLUMN_ID = 5;
    public static final int PROVIDING_NODE_COLUMN_ID = 6;

    public History() {
    }

    public String getMessage(int row) {
      return (String) getValueInternal(row, MESSAGE_COLUMN_ID);
    }

    public void setMessage(int row, String message) {
      setValueInternal(row, MESSAGE_COLUMN_ID, message);
    }

    public String getProvidingNode(int row) {
      return (String) getValueInternal(row, PROVIDING_NODE_COLUMN_ID);
    }

    public void setProvidingNode(int row, String providingNode) {
      setValueInternal(row, PROVIDING_NODE_COLUMN_ID, providingNode);
    }

    public String getReceiver(int row) {
      return (String) getValueInternal(row, RECEIVER_COLUMN_ID);
    }

    public void setReceiver(int row, String receiver) {
      setValueInternal(row, RECEIVER_COLUMN_ID, receiver);
    }

    public String getReceivingNode(int row) {
      return (String) getValueInternal(row, RECEIVING_NODE_COLUMN_ID);
    }

    public void setReceivingNode(int row, String receivingNode) {
      setValueInternal(row, RECEIVING_NODE_COLUMN_ID, receivingNode);
    }

    public String getSender(int row) {
      return (String) getValueInternal(row, SENDER_COLUMN_ID);
    }

    public void setSender(int row, String sender) {
      setValueInternal(row, SENDER_COLUMN_ID, sender);
    }

    public Date getTime(int row) {
      return (Date) getValueInternal(row, TIME_COLUMN_ID);
    }

    public void setTime(int row, Date time) {
      setValueInternal(row, TIME_COLUMN_ID, time);
    }

    public Integer getType(int row) {
      return (Integer) getValueInternal(row, TYPE_COLUMN_ID);
    }

    public void setType(int row, Integer type) {
      setValueInternal(row, TYPE_COLUMN_ID, type);
    }

    @Override
    public int getColumnCount() {
      return 7;
    }

    @Override
    public Object getValueAt(int row, int column) {
      switch (column) {
        case TYPE_COLUMN_ID:
          return getType(row);
        case SENDER_COLUMN_ID:
          return getSender(row);
        case RECEIVER_COLUMN_ID:
          return getReceiver(row);
        case MESSAGE_COLUMN_ID:
          return getMessage(row);
        case TIME_COLUMN_ID:
          return getTime(row);
        case RECEIVING_NODE_COLUMN_ID:
          return getReceivingNode(row);
        case PROVIDING_NODE_COLUMN_ID:
          return getProvidingNode(row);
        default:
          return null;
      }
    }

    @Override
    public void setValueAt(int row, int column, Object value) {
      switch (column) {
        case TYPE_COLUMN_ID:
          setType(row, (Integer) value);
          break;
        case SENDER_COLUMN_ID:
          setSender(row, (String) value);
          break;
        case RECEIVER_COLUMN_ID:
          setReceiver(row, (String) value);
          break;
        case MESSAGE_COLUMN_ID:
          setMessage(row, (String) value);
          break;
        case TIME_COLUMN_ID:
          setTime(row, (Date) value);
          break;
        case RECEIVING_NODE_COLUMN_ID:
          setReceivingNode(row, (String) value);
          break;
        case PROVIDING_NODE_COLUMN_ID:
          setProvidingNode(row, (String) value);
          break;
      }
    }
  }

  public static class Message extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Message() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class UserNameProperty extends AbstractPropertyData<String> {

    private static final long serialVersionUID = 1L;

    public UserNameProperty() {
    }
  }
}
